#!/bin/sh
redTxt="\e[91m"
greenTxt="\e[92m"
cyanTxt="\e[96m"
endColor="\e[0m"

printf "\n"$cyanTxt"[commit-msg] - Done "$endColor"\n";

msg=`cat $1`

msg=`echo "$msg" | sed 's/:tada:/🎉/'`
msg=`echo "$msg" | sed 's/:feat:/✨/'`
msg=`echo "$msg" | sed 's/:fix:/🐛/'`
msg=`echo "$msg" | sed 's/:hotfix:/🔥/'`
msg=`echo "$msg" | sed 's/:style:/🎨/'`
msg=`echo "$msg" | sed 's/:refactor:/💎/'`
msg=`echo "$msg" | sed 's/:release:/📦/'`
msg=`echo "$msg" | sed 's/:ci:/🤖/'`
msg=`echo "$msg" | sed 's/:build:/🤖/'`
msg=`echo "$msg" | sed 's/:test:/✅/'`
msg=`echo "$msg" | sed 's/:perf:/⚡/'`
msg=`echo "$msg" | sed 's/:docs:/📖/'`
msg=`echo "$msg" | sed 's/:doc:/📖/'`

exit 1
echo "$msg" > $1